#!/usr/bin/env node
/**
 * Generates the CSS custom properties the frontend consumes from the canonical
 * token set.
 *
 *   docs/brand-guidelines.md
 *     -> assets/design-tokens.json           (brand skill: sync-brand-to-tokens.cjs)
 *     -> main/frontend/src/styles/tokens.css (this script)
 *
 * The brand skill owns `primitive.color`; `semantic` is authored by hand in the
 * JSON. Only the brand ramp steps the product actually uses are emitted — the
 * skill's generated in-between shades are approximations and would invite
 * misuse if they became variables.
 */

const fs = require('fs');
const path = require('path');

const TOKENS_JSON = 'assets/design-tokens.json';
const OUT_CSS = 'main/frontend/src/styles/tokens.css';

// Brand ramp steps the product uses. 500 is the action colour, 600 its hover.
const BRAND_STEPS = ['500', '600'];
const BRAND_ROLES = { primary: 'brand', secondary: 'violet', accent: 'cyan' };

const val = node => (node && typeof node === 'object' && '$value' in node ? node.$value : node);

function lines(title, entries) {
  if (!entries.length) return [];
  return [`  /* ${title} */`, ...entries.map(([k, v]) => `  ${k}: ${v};`), ''];
}

function main() {
  const root = process.cwd();
  const tokensPath = path.resolve(root, TOKENS_JSON);
  if (!fs.existsSync(tokensPath)) {
    console.error(`Missing ${TOKENS_JSON}. Run the brand sync first.`);
    process.exit(1);
  }

  const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf-8'));
  const primitive = tokens.primitive?.color || {};
  const semantic = tokens.semantic || {};

  const brand = [];
  for (const [role, name] of Object.entries(BRAND_ROLES)) {
    for (const step of BRAND_STEPS) {
      const v = val(primitive[role]?.[step]);
      if (v) brand.push([`--color-${name}-${step}`, v]);
    }
  }

  const out = [
    '/* GENERATED by scripts/tokens-to-css.cjs — do not edit.',
    '   Edit docs/brand-guidelines.md, then re-run the sync. */',
    '',
    ':root {',
    ...lines('Brand', brand),
    ...lines('Surfaces & text', Object.entries(semantic.color || {}).map(([k, v]) => [`--color-${k}`, val(v)])),
    ...lines('Elevation', Object.entries(semantic.elevation || {}).map(([k, v]) => [`--elev-${k}`, val(v)])),
    ...lines('Radius', Object.entries(semantic.radius || {}).map(([k, v]) => [`--radius-${k}`, val(v)])),
    ...lines('Motion', Object.entries(semantic.motion || {}).map(([k, v]) => [`--${k}`, val(v)])),
    ...lines('Type', Object.entries(semantic.font || {}).map(([k, v]) => [`--font-${k}`, val(v)])),
  ];

  // Drop the trailing blank line before closing the block
  while (out[out.length - 1] === '') out.pop();
  out.push('}', '');

  const outPath = path.resolve(root, OUT_CSS);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out.join('\n'));

  const count = out.filter(l => l.trim().startsWith('--')).length;
  console.log(`Wrote ${OUT_CSS} (${count} variables)`);
}

main();
